export const APP_INIT = 'APP_INIT';
export const FIND_STOCKS_BY_WILDCARD_INVOKED = 'FIND_STOCKS_BY_WILDCARD_INVOKED';
export const FIND_STOCKS_BY_WILDCARD_SUCCESS = 'FIND_STOCKS_BY_WILDCARD_SUCCESS';

