export const APP_INIT = 'APP_INIT';
export const FIND_STOCKS_BY_WILDCARD_SUCCESS = 'FIND_STOCKS_BY_WILDCARD_SUCCESS';
export const GET_STOCK_HISTORICAL_DATA_SUCCESS = 'GET_STOCK_HISTORICAL_DATA_SUCCESS';
